const {
  InventoryLot,
  OfflineSaleItemLotAllocation,
} = require("../models");
const { logInventoryMovement, MOVEMENT_TYPES } = require("./inventoryMovementService");

const toPositiveInt = (value) => {
  const num = Number(value);
  if (!Number.isInteger(num) || num <= 0) {
    return null;
  }
  return num;
};

const buildLotCode = (productId) => {
  const stamp = Date.now().toString(36).toUpperCase();
  const suffix = Math.random().toString(36).slice(2, 6).toUpperCase();
  const productPart = String(productId || "").replace(/-/g, "").slice(0, 8).toUpperCase() || "PRODUCT";
  return `LOT-${productPart}-${stamp}-${suffix}`;
};

const createInventoryLot = async ({
  shopId,
  productId,
  quantity,
  sourceType,
  sourceRefId = null,
  note = null,
  unitCostMinor = null,
  createdByUserId = null,
  productQuantityBefore = 0,
  metadata = {},
  transaction,
}) => {
  const qty = toPositiveInt(quantity);
  if (!shopId || !productId || !qty) {
    throw new Error("shopId, productId and positive quantity are required to create inventory lot.");
  }

  const lot = await InventoryLot.create(
    {
      ShopId: shopId,
      ProductId: productId,
      lotCode: buildLotCode(productId),
      sourceType: String(sourceType || "UNKNOWN").slice(0, 60),
      sourceRefId: sourceRefId ? String(sourceRefId).slice(0, 120) : null,
      initialQty: qty,
      remainingQty: qty,
      unitCostMinor,
      status: "open",
      note: note ? String(note).slice(0, 255) : null,
      CreatedByUserId: createdByUserId || null,
      metadata: metadata && typeof metadata === "object" ? metadata : {},
    },
    { transaction }
  );

  await logInventoryMovement({
    shopId,
    productId,
    movementType: MOVEMENT_TYPES.IN,
    changeQty: qty,
    quantityAfter: productQuantityBefore + qty,
    reason: String(sourceType || "STOCK_IN").slice(0, 60),
    referenceType: "INVENTORY_LOT",
    referenceId: lot.id,
    note,
    createdByUserId,
    metadata: {
      lotId: lot.id,
      lotCode: lot.lotCode,
      ...(metadata && typeof metadata === "object" ? metadata : {}),
    },
    transaction,
  });

  return lot;
};

const getOpenLots = async ({ shopId, productId, transaction, lock = false }) =>
  InventoryLot.findAll({
    where: {
      ShopId: shopId,
      ProductId: productId,
      status: "open",
    },
    order: [["receivedAt", "ASC"], ["createdAt", "ASC"]],
    transaction,
    ...(lock ? { lock: transaction?.LOCK?.UPDATE } : {}),
  });

const ensureLotCoverageForProductStock = async ({
  shopId,
  product,
  createdByUserId = null,
  transaction,
}) => {
  const openLots = await getOpenLots({
    shopId,
    productId: product.id,
    transaction,
    lock: true,
  });

  const lotTrackedQty = openLots.reduce((sum, lot) => sum + Number(lot.remainingQty || 0), 0);
  const stockQty = Number(product.stock || 0);

  if (stockQty <= lotTrackedQty) {
    return;
  }

  const delta = stockQty - lotTrackedQty;

  await createInventoryLot({
    shopId,
    productId: product.id,
    quantity: delta,
    sourceType: "LEGACY_STOCK_SYNC",
    sourceRefId: product.id,
    note: "Auto-created lot to reconcile pre-existing stock with lot ledger.",
    createdByUserId,
    productQuantityBefore: stockQty - delta,
    metadata: {
      lotTrackedQty,
      stockQty,
      autoGenerated: true,
    },
    transaction,
  });
};

const consumeInventoryLotsFifo = async ({
  shopId,
  product,
  productVariantId = null,
  quantity,
  reason,
  referenceType = null,
  referenceId = null,
  note = null,
  createdByUserId = null,
  productQuantityBefore,
  offlineSaleItemId = null,
  metadata = {},
  transaction,
}) => {
  const qty = toPositiveInt(quantity);
  if (!shopId || !product?.id || !qty) {
    throw new Error("shopId, product and positive quantity are required for FIFO lot consumption.");
  }

  if (!Number.isInteger(productQuantityBefore) || productQuantityBefore < qty) {
    throw new Error("productQuantityBefore must be an integer and >= quantity.");
  }

  await ensureLotCoverageForProductStock({
    shopId,
    product,
    createdByUserId,
    transaction,
  });

  const lots = await getOpenLots({
    shopId,
    productId: product.id,
    productVariantId,
    transaction,
    lock: true,
  });

  const totalOpenQty = lots.reduce((sum, lot) => sum + Number(lot.remainingQty || 0), 0);
  if (totalOpenQty < qty) {
    throw new Error(
      `Insufficient lot quantity for ${product.name}. Tracked: ${totalOpenQty}, requested: ${qty}.`
    );
  }

  let remaining = qty;
  let runningProductQtyAfter = productQuantityBefore;
  const allocations = [];

  for (const lot of lots) {
    if (remaining <= 0) break;

    const lotAvailable = Number(lot.remainingQty || 0);
    if (lotAvailable <= 0) continue;

    const consumed = Math.min(remaining, lotAvailable);
    const lotRemainingAfter = lotAvailable - consumed;

    await lot.update(
      {
        remainingQty: lotRemainingAfter,
        status: lotRemainingAfter === 0 ? "consumed" : "open",
      },
      { transaction }
    );

    if (offlineSaleItemId) {
      await OfflineSaleItemLotAllocation.create(
        {
          OfflineSaleItemId: offlineSaleItemId,
          InventoryLotId: lot.id,
          quantity: consumed,
          unitCostMinorAtAllocation: lot.unitCostMinor,
          metadata: {
            lotCode: lot.lotCode,
          },
        },
        { transaction }
      );
    }

    runningProductQtyAfter -= consumed;

    await logInventoryMovement({
      shopId,
      productId: product.id,
      productVariantId: productVariantId || null,
      movementType: MOVEMENT_TYPES.OUT,
      changeQty: -consumed,
      quantityAfter: runningProductQtyAfter,
      reason: String(reason || "FIFO_STOCK_OUT").slice(0, 60),
      referenceType,
      referenceId,
      note,
      createdByUserId,
      metadata: {
        lotId: lot.id,
        lotCode: lot.lotCode,
        lotConsumedQty: consumed,
        lotRemainingAfter,
        ...(metadata && typeof metadata === "object" ? metadata : {}),
      },
      transaction,
    });

    allocations.push({
      lotId: lot.id,
      lotCode: lot.lotCode,
      quantity: consumed,
      lotRemainingAfter,
      unitCostMinorAtAllocation: lot.unitCostMinor,
    });

    remaining -= consumed;
  }

  return {
    allocations,
    quantityAfter: runningProductQtyAfter,
  };
};

module.exports = {
  createInventoryLot,
  consumeInventoryLotsFifo,
  ensureLotCoverageForProductStock,
};
